blank_issues_enabled: false
contact_links:
  - name: "Questions and Usage"
    url: "https://github.com/marcelojrrangel/netGrapql/discussions"
    about: "Use Discussions for questions and how-to topics."

