services:
  database:
    image: postgres:16-alpine
    container_name: graphql_pg_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: graphql_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  loki:
    image: grafana/loki:latest
    container_name: graphql_loki
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    volumes:
      - loki_data:/loki

  promtail:
    image: grafana/promtail:latest
    container_name: graphql_promtail
    volumes:
      - ../log:/var/log/graphql
      - ../../GraphQLPlayground.Console/log:/var/log/graphql-console
      - ./promtail.yml:/etc/promtail/promtail.yml
    command: -config.file=/etc/promtail/promtail.yml
    depends_on:
      - loki

  grafana:
    image: grafana/grafana:latest
    container_name: graphql_grafana
    ports:
      - "3000:3000"
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/dashboards:/var/lib/grafana/dashboards
    depends_on:
      - loki

volumes:
  pgdata:
  loki_data:
  grafana_data: